### ISSUE TITLE
`segfault-handler` breaks cross-architecture build

### ISSUE THREAD

**Issue by MainAero** [zeebe-io/zeebe-client-node-js#173]
The introduced usage of [segfault-handler](https://github.com/zeebe-io/zeebe-client-node-js/commit/5cb03c7d65411a40621b160a12b8932b0cd2e9ce#diff-d18ca08a1129250d4a8566527645fdaf) breaks our cross-architecture build.
We didn't find any way on rebuilding `segfault-handler` to work in a AWS Lambda function expect the way of using a docker image. As this would introduce a lot of refactoring of our CI pipeline we decided to remove `segfault-handler` in our [fork](https://github.com/mineko-io/zeebe-client-node-js/commit/4663419653a66e8f4369dd5e621f49afaaadbce4).

The AWS Lambda fails with:

```
ERROR	Error: /var/task/node_modules/segfault-handler/build/Release/segfault-handler.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/task/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

**Comment by bhsdodo** [comment]
Just to add more issues about `segfault-handler` package:

The library has some issues when running in Alpine Linux images:
https://github.com/ddopson/node-segfault-handler/issues/70
https://github.com/ddopson/node-segfault-handler/pull/67

Looks like they are not maintaining that package anymore.

**Comment by jwulf** [comment]
Yah, got it. I'll do another release without this dependency.
